### ISSUE TITLE
error while reading xlsx

### ISSUE THREAD

**Issue by motivatedmind** [millij/poi-object-mapper#34]
I am reading xlsx as below.

```
  public static void main(String[] args) throws SpreadsheetReadException {
    final File xlsxFile = new File("target/pages-1.xlsx");
    final XlsxReader reader = new XlsxReader ();
    List<Model> models = reader.read(Model.class, xlsxFile);
    System.out.println(models.toString());
  }

```

Getting this error when i try to print my pojo:

```
Exception in thread "main" java.lang.NoSuchMethodError: org/apache/poi/xssf/eventusermodel/XSSFSheetXMLHandler.<init>(Lorg/apache/poi/xssf/model/StylesTable;Lorg/apache/poi/xssf/eventusermodel/ReadOnlySharedStringsTable;Lorg/apache/poi/xssf/eventusermodel/XSSFSheetXMLHandler$SheetContentsHandler;Z)V (loaded from file:/C:/Users/.m2/repository/org/apache/poi/poi-ooxml/4.1.2/poi-ooxml-4.1.2.jar by sun.misc.Launcher$AppClassLoader@722e609e) called from class io.github.millij.poi.ss.reader.XlsxReader (loaded from file:/C:/Users/.m2/repository/io/github/millij/poi-object-mapper/1.0.0/poi-object-mapper-1.0.0.jar by sun.misc.Launcher$AppClassLoader@722e609e).
	at io.github.millij.poi.ss.reader.XlsxReader.read(XlsxReader.java:65)
	at io.github.millij.poi.ss.reader.AbstractSpreadsheetReader.read(AbstractSpreadsheetReader.java:82)
	at io.github.millij.poi.ss.reader.XlsxReader.read(XlsxReader.java:31)
	at io.github.millij.poi.ss.reader.AbstractSpreadsheetReader.read(AbstractSpreadsheetReader.java:69)
	at io.github.millij.poi.ss.reader.XlsxReader.read(XlsxReader.java:31)
	at com.motivatedmind.scrapper.example2.tempprad.main(tempprad.java:15)
```

Dependency versions :

```
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi</artifactId>
      <version>4.1.2</version>
    </dependency>
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml</artifactId>
      <version>4.1.2</version>
    </dependency>
	<dependency>
      <groupId>io.github.millij</groupId>
      <artifactId>poi-object-mapper</artifactId>
      <version>1.0.0</version>
    </dependency>
```

**Note : I am successfully able to write pojo to xlsx**

**Comment by millij** [comment]
@motivatedmind 
You're getting this error due to the version mismatch.

`poi-object-mapper` version `1.0.0` depends on - POI Version `3.17`

In your dependencies, you're using POI - `4.1.2`
for POI - `4.+` support, use the below snapshot of `poi-object-mapper` 
[2.0.0-SNAPSHOT](https://github.com/millij/poi-object-mapper/releases/tag/2.0.0)

**Comment by motivatedmind** [comment]
@millij Thanks it works. I reverted my poi version to 3.17
